# prometheus.yml
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'FSight'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: goapp
    scrape_interval: 10s
    static_configs:
       - targets: ['localhost:2112']
