# prometheus.yml
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'GoApp'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: GoApplication
    scrape_interval: 5s
    static_configs:
       - targets: ['Gmail:2345']
